### PR TITLE
63 update user profile

### PR DESCRIPTION
**Pull request by EvangeliaSp**
* Added field with password in user's profile (dots instead of password)
* Added button for update password, where user is asked to put their current password and the new twice.
  * Alert windows in case of error (empty passwords, confirm password is not the same with the new password, old password is not the right one)
  * Handled all the possible errors from backend
  * Fixed bug in the backend - in case of password update save the hash and not the password (we were saving the password)
* Added button for Edit Profile, where a popup opens with all the fields that the user can update (all except for email and password). In the boxes the current values are shown. The user does not need to update all the fields.
* After successful password update, a new popup is shown where the user must press ok to go to the login page and log in with the new password - the localStorage is cleaned so the session of the user is deleted and the user must log in again

### CODE REVIEW

**Comment by knikamo** [comment]
Wow great job @EvangeliaSp ! I think it looks good, maybe use another color on the update password button? Red looks a little bit dangerous haha.

I just tried to put a street number with a letter (1A) and then all fields says "undefined" except e-mail. In my database the user is unchanged, which is good. We don't really handle input types which I think is okay, and maybe we need to prioritize other things. So I approve merging this branch but I'll let @nicolets and @mikaelamch have a look first!

**Comment by EvangeliaSp** [comment]
> Wow great job @EvangeliaSp ! I think it looks good, maybe use another color on the update password button? Red looks a little bit dangerous haha.

Thank you @knikamo ! Haha yes I know, I didn't know which to choose, any idea? 

> I just tried to put a street number with a letter (1A) and then all fields says "undefined" except e-mail. In my database the user is unchanged, which is good. We don't really handle input types which I think is okay, and maybe we need to prioritize other things. 

 I don't understand, do u mean when you try to update the user info? The truth is that we don't handle the input types but yes it is ok. But what is the result, does it crash?

**Comment by knikamo** [comment]
> > Wow great job @EvangeliaSp ! I think it looks good, maybe use another color on the update password button? Red looks a little bit dangerous haha.
> 
> Thank you @knikamo ! Haha yes I know, I didn't know which to choose, any idea?

I was thinking of something more neutral, like grey maybe?
> 
> > I just tried to put a street number with a letter (1A) and then all fields says "undefined" except e-mail. In my database the user is unchanged, which is good. We don't really handle input types which I think is okay, and maybe we need to prioritize other things.
> 
> I don't understand, do u mean when you try to update the user info? The truth is that we don't handle the input types but yes it is ok. But what is the result, does it crash?

Yes exactly when I update user info, when I click "update" the popup closes and all fields just says "undefined".

**Comment by EvangeliaSp** [comment]
> I was thinking of something more neutral, like grey maybe?

Yes fine! I'll change it tomorrow, or you can also change it if you want!

> Yes exactly when I update user info, when I click "update" the popup closes and all fields just says "undefined".

I think we don't even handle these errors in the backend :P If we have time in the end, we can do something for it!

**Comment by knikamo** [comment]
I've changed the color of the button to white (and grey when hovering)

**Pull request merged**
